<?php

namespace Digeetis\APIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AggregateStreamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AggregateStreamRepository extends EntityRepository
{
}
