<?php

namespace Digeetis\APIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleStreamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleStreamRepository extends EntityRepository{
    
    public function getArticlesFromStreamByLimitOrder($stream, $limit=10,$order='DESC'){
        $qb = $this->createQueryBuilder("m");
        $qb
        ->add("select", "m")
        ->add("where", "m.stream = :stream")
        ->add('orderBy', "m.dateUpdate :order")
        ->add("limit", ":limit")
        ->setParameters(array(':stream'=>$stream, ':order'=>$order, ':limit'=>$limit));
        return $qb->getQuery()->getResult();
    }
    
}
